var files =
[
    [ "Code/main_entry_point.cpp", "main__entry__point_8cpp.html", "main__entry__point_8cpp" ],
    [ "Code/sensors.cpp", "sensors_8cpp.html", null ],
    [ "Code/sensors.h", "sensors_8h.html", null ],
    [ "Code/testing.cpp", "testing_8cpp.html", null ],
    [ "Code/testing.h", "testing_8h.html", null ],
    [ "Code/tools.cpp", "tools_8cpp.html", null ],
    [ "Code/tools.h", "tools_8h.html", "tools_8h" ],
    [ "Code/Client/xbox.cpp", "xbox_8cpp.html", null ],
    [ "Code/Client/xbox.h", "xbox_8h.html", null ],
    [ "Code/Definitions/components.cpp", "components_8cpp.html", null ],
    [ "Code/Definitions/components.h", "components_8h.html", null ],
    [ "Code/Definitions/ports.h", "ports_8h.html", "ports_8h" ],
    [ "Code/Profiles/MainRobot.cpp", "_main_robot_8cpp.html", null ],
    [ "Code/Profiles/MainRobot.h", "_main_robot_8h.html", null ],
    [ "Code/Profiles/PrototypeRobot.cpp", "_prototype_robot_8cpp.html", null ],
    [ "Code/Profiles/PrototypeRobot.h", "_prototype_robot_8h.html", null ],
    [ "Code/Subsystems/arm.cpp", "arm_8cpp.html", null ],
    [ "Code/Subsystems/arm.h", "arm_8h.html", null ],
    [ "Code/Subsystems/driving.cpp", "driving_8cpp.html", null ],
    [ "Code/Subsystems/driving.h", "driving_8h.html", null ],
    [ "Code/Subsystems/elevator.cpp", "elevator_8cpp.html", null ],
    [ "Code/Subsystems/elevator.h", "elevator_8h.html", null ],
    [ "Code/Subsystems/filter.cpp", "filter_8cpp.html", "filter_8cpp" ],
    [ "Code/Subsystems/filters.h", "filters_8h.html", "filters_8h" ],
    [ "Code/Subsystems/shooter.cpp", "shooter_8cpp.html", null ],
    [ "Code/Subsystems/shooter.h", "shooter_8h.html", null ],
    [ "Code/Tracking/target.cpp", "target_8cpp.html", "target_8cpp" ],
    [ "Code/Tracking/target.h", "target_8h.html", "target_8h" ],
    [ "Code/Tracking/track_silver.cpp", "track__silver_8cpp.html", null ],
    [ "Code/Tracking/track_silver.h", "track__silver_8h.html", null ]
];